In [1]:
puzzle = [[5, 3, 0, 0, 7, 0, 0, 0, 0],
         [6, 0, 0, 1, 9, 5, 0, 0, 0],
         [0, 9, 8, 0, 0, 0, 0, 6, 0],
         [8, 0, 0, 0, 6, 0, 0, 0, 3],
         [4, 0, 0, 8, 0, 3, 0, 0, 1],
         [7, 0, 0, 0, 2, 0, 0, 0, 6],
         [0, 6, 0, 0, 0, 0, 2, 8, 0],
         [0, 0, 0, 4, 1, 9, 0, 0, 5],
         [0, 0, 0, 0, 8, 0, 0, 0, 0]]

In [2]:
import numpy as np

In [3]:
def fill(x, y, n):
    global puzzle
    for n in range(n, 10):
        flag = True
        x1 = (x // 3) * 3
        y1 = (y // 3) * 3
        for i in range(x1, x1+3):
            for j in range(y1, y1+3):
                if puzzle[j][i] == n:
                    flag = False
                    
        for i in range(9):
            if puzzle[y][i] == n or puzzle[i][x] == n:
                flag = False
                
        if flag:        
            return n
    
    return None

In [4]:
print(fill(2, 0, 1))
print(fill(4, 4, 1))

1
5


In [5]:
def find(i, j):
    global puzzle
    is_zero = False
    for y in range(9):
        for x in range(9):
            if puzzle[y][x] == 0:
                is_zero = True
    if is_zero == False:
        print(np.matrix(puzzle))
        input("\nAnother Solution?\n")
    #print(is_zero)
    puzzle[j][i] = fill(i, j, puzzle[j][i] + 1)
    #print(np.matrix(puzzle), "\n")
    if puzzle[j][i] != None:
        solve()
        find(i, j)
    else:
        puzzle[j][i] = 0
        return

In [6]:
def solve():
    global puzzle
    for j in range(9):
        for i in range(9):
            if puzzle[j][i] == 0:
                find(i, j)
                return

In [7]:
solve()

[[5 3 4 6 7 8 1 9 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 9 7 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 7 1 9]]

Another Solution?

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]

Another Solution?

