In [1]:
#sudoku to be solved
puzzle = [[5, 3, 0, 0, 7, 0, 0, 0, 0],
         [6, 0, 0, 1, 9, 5, 0, 0, 0],
         [0, 9, 8, 0, 0, 0, 0, 6, 0],
         [8, 0, 0, 0, 6, 0, 0, 0, 3],
         [4, 0, 0, 8, 0, 3, 0, 0, 1],
         [7, 0, 0, 0, 2, 0, 0, 0, 6],
         [0, 6, 0, 0, 0, 0, 2, 8, 0],
         [0, 0, 0, 4, 1, 9, 0, 0, 5],
         [0, 0, 0, 0, 8, 0, 0, 0, 0]]

In [2]:
import numpy as np
from copy import deepcopy     #importing this library to copy lists 
solutions = []

In [3]:
def fill(x, y, n):       #x postion, y position and n = from which number the search is to be initiated
    global puzzle        #using global keyword with the variable to modify the variable inside the function
    for n in range(n, 10):
        flag = True
        
        #figuring out the presence of number in 3*3 square boxes
        x1 = (x // 3) * 3
        y1 = (y // 3) * 3
        for i in range(x1, x1+3):
            for j in range(y1, y1+3):
                if puzzle[j][i] == n:
                    flag = False
         
        #figuring out the presence of number in horizontal or vertical line
        for i in range(9):
            if puzzle[y][i] == n or puzzle[i][x] == n:
                flag = False
                
        if flag:        
            return n
    
    return None

In [4]:
print(fill(2, 0, 1))
print(fill(4, 4, 1))

1
5


In [5]:
def find(i, j):
    global puzzle             #using global keyword with the variable to modify the variable inside the function
    is_zero = False
    
    #checking if there is empty slot to be updated characterized by number '0'
    for y in range(9):
        for x in range(9):
            if puzzle[y][x] == 0:
                is_zero = True
    
    #printing the solution and appending it if there is no empty slot
    if is_zero == False:
        print(np.matrix(puzzle))
        result = deepcopy(puzzle)
        solutions.append(result)
        input("\nAnother Solution?\n")
        
    #print(is_zero)
    puzzle[j][i] = fill(i, j, puzzle[j][i] + 1)     #finding a number to fill the slot in the puzzle
    #print(np.matrix(puzzle), "\n")
    
    #if a number is found to be filled in the empty slot, solve for next slot; else make it the empty slot again by 
    #by inserting number '0' in the slot and return to the previous slot
    if puzzle[j][i] != None:
        solve()
        find(i, j)
    else:
        puzzle[j][i] = 0
        return

In [6]:
def solve():
    global puzzle             #using global keyword with the variable to modify the variable inside the function
    for j in range(9):
        for i in range(9):
            if puzzle[j][i] == 0:      #checking if there is any empty slot to be filled
                find(i, j)
                return

In [7]:
solve()

[[5 3 4 6 7 8 1 9 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 9 7 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 7 1 9]]

Another Solution?

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]

Another Solution?



In [8]:
solutions

[[[5, 3, 4, 6, 7, 8, 1, 9, 2],
  [6, 7, 2, 1, 9, 5, 3, 4, 8],
  [1, 9, 8, 3, 4, 2, 5, 6, 7],
  [8, 5, 9, 7, 6, 1, 4, 2, 3],
  [4, 2, 6, 8, 5, 3, 9, 7, 1],
  [7, 1, 3, 9, 2, 4, 8, 5, 6],
  [9, 6, 1, 5, 3, 7, 2, 8, 4],
  [2, 8, 7, 4, 1, 9, 6, 3, 5],
  [3, 4, 5, 2, 8, 6, 7, 1, 9]],
 [[5, 3, 4, 6, 7, 8, 9, 1, 2],
  [6, 7, 2, 1, 9, 5, 3, 4, 8],
  [1, 9, 8, 3, 4, 2, 5, 6, 7],
  [8, 5, 9, 7, 6, 1, 4, 2, 3],
  [4, 2, 6, 8, 5, 3, 7, 9, 1],
  [7, 1, 3, 9, 2, 4, 8, 5, 6],
  [9, 6, 1, 5, 3, 7, 2, 8, 4],
  [2, 8, 7, 4, 1, 9, 6, 3, 5],
  [3, 4, 5, 2, 8, 6, 1, 7, 9]]]